version: 0.1.2.dev8+g49bd5b8a7.d20251218
output_dir: .
device_type: cuda
n_iterations: 1
memory: false
parameterisation_settings:
    smiles: "C"
    initial_force_field: /home/campus.ncl.ac.uk/nfc78/software/devel/bespokefit-smee-benchmarking-clean/workflow/jacs_set_conformers_frags_torsions/output/md_then_tor_min_longer_mm_ens_all_ml_energy_no_restr_energy_only_torsions_only/combined_pretrained.offxml
    expand_torsions: true
    linearise_harmonics: true
    type_generation_settings: {}
training_sampling_settings:
    sampling_protocol: mm_md_metadynamics_torsion_minimisation
    ml_potential: egret-1
    timestep: 1 fs
    temperature: 500 K
    snapshot_interval: 500 fs
    n_conformers: 10
    equilibration_sampling_time_per_conformer: 0.1 ps
    production_sampling_time_per_conformer: 20 ps
    loss_energy_weight: 1000.0
    loss_force_weight: 0.1
    metadynamics_bias_factor: 10.0
    bias_width: 0.3141592653589793
    bias_factor: 10.0
    bias_height: 2.0 kJ * mol**-1
    bias_frequency: 0.5 ps
    bias_save_frequency: 1.0 ps
    ml_minimisation_steps: 10
    mm_minimisation_steps: 10
    torsion_restraint_force_constant: 0.0 kcal * rad**-2 * mol**-1
    loss_energy_weight_mmmd: 0
    loss_force_weight_mmmd: 0.0
    loss_energy_weight_torsion_min: 1000.0
    loss_force_weight_torsion_min: 0
testing_sampling_settings:
    sampling_protocol: mm_md_metadynamics_torsion_minimisation
    ml_potential: egret-1
    timestep: 1 fs
    temperature: 500 K
    snapshot_interval: 4 ps
    n_conformers: 10
    equilibration_sampling_time_per_conformer: 0.1 ps
    production_sampling_time_per_conformer: 20 ps
    loss_energy_weight: 1000.0
    loss_force_weight: 0.1
    metadynamics_bias_factor: 10.0
    bias_width: 0.3141592653589793
    bias_factor: 10.0
    bias_height: 2.0 kJ * mol**-1
    bias_frequency: 0.5 ps
    bias_save_frequency: 1.0 ps
    ml_minimisation_steps: 10
    mm_minimisation_steps: 10
    torsion_restraint_force_constant: 0.0 kcal * rad**-2 * mol**-1
    loss_energy_weight_mmmd: 1000.0
    loss_force_weight_mmmd: 0.1
    loss_energy_weight_torsion_min: 1000.0
    loss_force_weight_torsion_min: 0.1
training_settings:
    optimiser: adam
    parameter_configs:
        ProperTorsions:
            cols:
            - k
            scales:
                k: 1.3
            limits:
                k:
                - null
                - null
            regularize:
                k: 1.0
            include: null
            exclude:
            -   id: '[*:1]-[*:2]#[*:3]-[*:4]'
                mult: null
                associated_handler: null
                bond_order: null
            -   id: '[*:1]~[*:2]-[*:3]#[*:4]'
                mult: null
                associated_handler: null
                bond_order: null
            -   id: '[*:1]~[*:2]=[#6,#7,#16,#15;X2:3]=[*:4]'
                mult: null
                associated_handler: null
                bond_order: null
    attribute_configs: {}
    n_epochs: 1000
    learning_rate: 0.01
    learning_rate_decay: 1.0
    learning_rate_decay_step: 10
    regularisation_target: initial
